import express from 'express';
import { verifyEmail, resendEmail } from '../controllers/emailAuthController.js';
import upload from '../middleware/song_upload.js';
import authMiddleware from '../middleware/customer_auth.js';
import artistAuthMiddleware from '../middleware/artist_auth.js';
import {uploadLimiter, registerLimiter} from '../middleware/rate_limiter.js' //limit amount of times someone can upload
import {
    register,
    login,
    updateS3Key,
    deleteAccount,
    changePassword,
    getUserProfile,



  
} from '../controllers/authController.js';

//i know there are routes in here that should be in other route.js files. However, I am learning as i go and this project has quickly developed in size.

//I will move the appropriate files to the appropriate folders as i go.

//define the router. This will handle the routes and be used to handle requests from the frontend.
const router = express.Router();

//deal with registration first. This will handle user registrations. Post ensures that the data is sent in the body of the request.
router.post('/register', registerLimiter, register);;

//now let us deal with login. We will use post again, in order to send the data to the client.
router.post('/login', login)

router.post('/delete-account', deleteAccount);

router.post('/change-password', changePassword);

router.get('/get-profile', getUserProfile);



router.get('/verify-email', verifyEmail);
//all verify email logic generated by AI so i have a base to work on tomorrow. come back to it and fix!

router.post('/resend-email', resendEmail);
//update S3 File for ID's that were not initially added.
router.put('/updateS3/:id', authMiddleware, updateS3Key);

export default router;

//move track files into tracks.js